;(function($){$.myURL||($.extend({myURL:function(c){$.myURL.defaults.base||$.myURL.config();if(c){var a,b=$.myURL.defaults.base;if("index"==c)b+="/index.php",a=Array.prototype.slice.call(arguments,1);else{if("pathname"==c)return window.location.pathname;if("afterpath"==c)return window.location.href.substr(window.location.href.indexOf(window.location.pathname)+window.location.pathname.length);if("fullpathname"==c)return $.myURL("pathname")+$.myURL("afterpath");a=Array.prototype.slice.call(arguments)}if(0<
a.length){var e=[],d=void 0;for(x in a)if("string"===typeof a[x])""==!a[x]&&("/"==a[x].charAt(0)&&(a[x]=a[x].substring(1)),"/"==a[x].charAt(a[x].length-1)&&(a[x]=a[x].substring(0,a[x].length-1)),""==!a[x]&&(e[x]=a[x]));else if("object"===typeof a[x]){var f=!1;if(0<e.length)for(y in e)-1<e[y].indexOf("?")&&(f=!0);if("[object Array]"===Object.prototype.toString.call(a[x]))for(y in a[x])if("string"==typeof a[x][y])d+=(f?"&":d?-1<d.indexOf("?")?"&":"?":"?")+a[x][y];else{if("object"==typeof a[x][y])var g=
a[x][y].key+"="+a[x][y].value,d=d?d+((-1<d.indexOf("?")?"&":f?"&":"?")+g):(f?"&":"?")+g}else d=d?d+((-1<d.indexOf("?")?"&":f?"&":"?")+$.param(a[x])):(f?"&":"?")+$.param(a[x])}0<e.length&&(b=b+"/"+e.join("/"));d&&(-1<b.indexOf("/?")&&(b=b.replace("/?","?")),b+=d)}b=$.myURL.defaults.trail?b.charAt(b.length-1)?b+"/":b:b;a=b.split("/");if(a[""==a[a.length-1]?a.length-2:a.length-1].match(/.[.,!,@,#,$,%,^,&,*,?,_,~]/))"/"==b.charAt(b.length-1)&&(b=b.substring(0,b.length-1));return b}b=$.myURL.defaults.base;
return b=$.myURL.defaults.trail?b.charAt(b.length-1)?b+"/":b:b}}),$.myURL.config=function(c){var a=location.href;if(c)$.myURL.defaults.isLocal=c.isLocal?!0:0<=a.indexOf("//local")?!0:!1,c.forceMain&&($.myURL.defaults.forceMain=c.forceMain),c.local&&(c.local.main&&($.myURL.defaults.dirs.local.main=c.local.main),c.local.sub&&($.myURL.defaults.dirs.local.sub=c.local.sub)),c.onSite&&(c.onSite.main&&($.myURL.defaults.dirs.onSite.main=c.onSite.main),c.onSite.sub&&($.myURL.defaults.dirs.onSite.sub=c.onSite.sub)),
c.trail&&($.myURL.defaults.trail=c.trail);else{c={};var b=a.substring(a.indexOf(window.location.hostname)).split("/");2<=b.length&&(""!=b[1]&&!b[1].match(/.[.,!,@,#,$,%,^,&,*,?,_,~]/))&&($.myURL.defaults.mainDir=b[1],3<=b.length&&(b.splice(0,2),c=[],c=function(){var a=[];for(x in b)if(""!=b[x]&&!b[x].match(/.[.,!,@,#,$,%,^,&,*,?,_,~]/))a[x]=b[x];else break;return a},0<c.length&&($.myURL.defaults.subDir=c.join("/"))))}$.myURL.defaults.isLocal?$.myURL.defaults.dirs.local.main&&(a=a.substring(a.indexOf($.myURL.defaults.dirs.local.main)).substring(0,
a.substring(a.indexOf($.myURL.defaults.dirs.local.main)).indexOf("/")),$.myURL.defaults.dirs.local.main==a&&($.myURL.defaults.mainDir=$.myURL.defaults.dirs.local.main),$.myURL.defaults.dirs.local.sub&&($.myURL.defaults.subDir=$.myURL.defaults.dirs.local.sub)):$.myURL.defaults.dirs.onSite.main&&($.myURL.defaults.forceMain?$.myURL.defaults.dirs.onSite.main&&($.myURL.defaults.mainDir=$.myURL.defaults.dirs.onSite.main):(a=a.substring(a.indexOf($.myURL.defaults.dirs.onSite.main)).substring(0,a.substring(a.indexOf($.myURL.defaults.dirs.onSite.main)).indexOf("/")),
$.myURL.defaults.dirs.onSite.main==a&&($.myURL.defaults.mainDir=$.myURL.defaults.dirs.onSite.main)),$.myURL.defaults.dirs.onSite.sub&&($.myURL.defaults.subDir=$.myURL.defaults.dirs.onSite.sub));$.myURL.defaults.base=window.location.protocol+"//"+window.location.hostname;$.myURL.defaults.mainDir&&($.myURL.defaults.base=$.myURL.defaults.base+"/"+$.myURL.defaults.mainDir);$.myURL.defaults.subDir&&($.myURL.defaults.base=$.myURL.defaults.base+"/"+$.myURL.defaults.subDir)},$.myURL.defaults={base:void 0,
dirs:{local:{main:void 0,sub:void 0},onSite:{main:void 0,sub:void 0}},forceMain:!0,isLocal:!1,mainDir:void 0,subDir:void 0,trail:!0})})(jQuery);

